# Generated by Django 4.0.10 on 2023-03-21 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('travel_order', models.PositiveIntegerField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('stay_time', models.DurationField(blank=True, null=True)),
                ('next_destination_mode', models.CharField(blank=True, max_length=200, null=True)),
                ('next_destination_travel_time', models.DurationField(blank=True, null=True)),
            ],
            options={
                'ordering': ['travel_order'],
            },
        ),
    ]
