# Generated by Django 4.0.10 on 2023-03-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
