# Generated by Django 4.0.10 on 2023-03-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_userprofile_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
